### ISSUE TITLE
WSL asset build fail  ERROR  ENOENT: no such file or directory, lstat ..../assets

### ISSUE THREAD

**Issue by menguzat** [ramyma/a8r8#13]
I downloaded install.sh and ran in my WSL2 ubuntu container with node version 21

everything downloaded and the setup proceeded to almost 100%

but then:

Adding debian:ACCVRAIZ1.pem
Adding debian:Entrust_Root_Certification_Authority_-_EC1.pem
Adding debian:Entrust_Root_Certification_Authority_-_G4.pem
done.
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
Processing triggers for libc-bin (2.35-0ubuntu3.6) ...
/sbin/ldconfig.real: /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Processing triggers for ca-certificates (20230311ubuntu0.22.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
Processing triggers for shared-mime-info (2.1-2) ...
Skipping git clone
Plugin named nodejs already added
Plugin named erlang already added
Plugin named elixir already added
Plugin named rust already added
Either specify a tool & version in the command
OR add .tool-versions file in this directory
or in a parent directory

added 1 package in 4s

1 package is looking for funding
  run `npm fund` for details
 ERROR  ENOENT: no such file or directory, lstat '/home/meng/a8/assets'
For help, run: pnpm help install
 ERROR  ENOENT: no such file or directory, lstat '/home/meng/a8/assets'
For help, run: pnpm help run
Assets build failed!

running install.sh again:

xsltproc is already the newest version (1.1.34-4ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
Skipping git clone
Plugin named nodejs already added
Plugin named erlang already added
Plugin named elixir already added
Plugin named rust already added
Either specify a tool & version in the command
OR add .tool-versions file in this directory
or in a parent directory

changed 1 package in 898ms

1 package is looking for funding
  run `npm fund` for details
 ERR_PNPM_NO_PKG_MANIFEST  No package.json found in /home/meng/a8/assets
 ERR_PNPM_NO_IMPORTER_MANIFEST_FOUND  No package.json (or package.yaml, or package.json5) was found in "/home/meng/a8/assets".
Assets build failed!

what may be causing this?

**Comment by ramyma** [comment]
If you want to run the install script manually (not using the [one-click-installer-wsl.bat
](https://github.com/ramyma/a8r8/blob/main/one-click-)), you'll need to run `CLONE_REPO=true ./install.sh`

**Comment by menguzat** [comment]
yes that solved it. 
I already had a wsl installation so didn't want to go through with setting up a new one.
maybe add to the readme?

**Comment by menguzat** [comment]
closing

**Comment by ramyma** [comment]
@menguzat do you mind if we connect on Discord?

**Comment by ramyma** [comment]
Starting Forge before running A8R8 should work, unless there's a network issue between  wsl and windows that we need to explore

**Comment by ramyma** [comment]
Should be fixed by #14
