### ISSUE TITLE
Can't install on Windows 11

### ISSUE THREAD

**Issue by Michoko92** [ramyma/a8r8#17]
Hi,

I'd like to test this UI, but when I try to install it with the installer script on French Windows 11 (Powershell), I get errors. Here is the output (translated from French):

```
PS D:\AI> .\one-click-installer-wsl.bat

D:\AI>wsl --install -d ubuntu --no-launch
Ubuntu is already installed.
Operation successful.

D:\AI>wsl -d ubuntu -e bash -c "CLONE_REPO=true ./install.sh"
There is no distribution with this name.
Error code: Wsl/Service/WSL_E_DISTRO_NOT_FOUND

D:\AI>echo 'If instalaltion was successfull, run the ".\run-windows.bat" file in the created "a8r8" folder to start the application'
'If instalaltion was successfull, run the ".\run-windows.bat" file in the created "a8r8" folder to start the application'
```

There is no "a8r8" folder created. Do you have a suggestion, please? Thank you!

**Comment by ramyma** [comment]
Looks like WSL wasn't installed correctly.

**Comment by ramyma** [comment]
Did you try restarting your machine after running the script the first time?

WSL installation requires a reboot on the first run.

**Comment by ramyma** [comment]
Or you can try this:
https://github.com/microsoft/WSL/issues/9338#issuecomment-1499692107

**Comment by ramyma** [comment]
Or this solution if the issue still persists:
https://github.com/microsoft/WSL/issues/9338#issuecomment-1564168723

**Comment by Michoko92** [comment]
> Or you can try this: [microsoft/WSL#9338 (comment)](https://github.com/microsoft/WSL/issues/9338#issuecomment-1499692107)

Thank you, this did the trick 🙂
