### ISSUE TITLE
Potentially unable to install if WSL is already installed

### ISSUE THREAD

**Issue by Euchale** [ramyma/a8r8#18]
I am on Windows 10 and already have Windows Subsystem for Linux installed. This is what the terminal says:

```

D:\SD-Storage\ComfyUIA8R8Hook>.\one-click-installer-wsl.bat

D:\SD-Storage\ComfyUIA8R8Hook>wsl --install -d ubuntu --no-launch
Ubuntu is already installed.
The requested operation is successful. Changes will not be effective until the system is rebooted.

D:\SD-Storage\ComfyUIA8R8Hook>wsl -d ubuntu -e bash -c "CLONE_REPO=true ./install.sh"
This application requires the Windows Subsystem for Linux Optional Component.
Install it by running: wsl.exe --install --no-distribution
The system may need to be restarted so the changes can take effect.
Error code: Wsl/WSL_E_WSL_OPTIONAL_COMPONENT_REQUIRED

D:\SD-Storage\ComfyUIA8R8Hook>echo 'If instalaltion was successfull, run the ".\run-windows.bat" file in the created "a8r8" folder to start the application'
'If instalaltion was successfull, run the ".\run-windows.bat" file in the created "a8r8" folder to start the application'
```
It generated nothing in the folder the file is in.

**Comment by ramyma** [comment]
Can you share the Windows build number?
https://www.howtogeek.com/236195/how-to-find-out-which-build-and-version-of-windows-10-you-have/

**Comment by Euchale** [comment]
![image](https://github.com/ramyma/a8r8/assets/3716287/7bf686e1-ecfc-430b-971d-ac7bd83c43e7)

**Comment by ramyma** [comment]
Can you run `wsl -l -v` to get the WSL version?

Also, I'm available on discord if you want a direct response, I can guide through it if you want.

**Comment by ramyma** [comment]
Looks like restarting the machine did the trick.
@Euchale Please let me know if we can close the this issue.

**Comment by Euchale** [comment]
Full guide that fixed it for me:
Install via .\one-click-installer-wsl.bat
Restart PC
Run .\one-click-installer-wsl.bat twice 

Can be closed.
