### ISSUE TITLE
you must be crazy to force ppl to install linux in windows to use sd pal

### ISSUE THREAD

**Issue by 3blackbar** [ramyma/a8r8#20]
Why would anyone want to do that ?
Your feature set is good but regular gui that runs in the browser would be nice

**Comment by ramyma** [comment]
Well, no one is forcing anyone to do anything, it's available and it's free!

The only reason that it requires WSL is to be able to use some dependencies that don't support Windows.

Anyway, any constructive criticism is welcomed.
