### ISSUE TITLE
Installation problems (Docker)

### ISSUE THREAD

**Issue by MoreColors123** [ramyma/a8r8#8]
Seems to be a very promising tool. I had some troubles yesterday installing it though, and I'm sorry but I can't tell anymore why the recommended method didn't work, I didn't save the logs. 

But I tried the docker mode too now and there also was a problem. It seems Powershell didn't have the rights and so i had to set this in powershell: 
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned

And then run install-docker.ps1
But in Powershell _without_ admin rights!

**Comment by ramyma** [comment]
Which version of Windows are you on?

Also, are you still stuck with either method of installation?

I appreciate your feedback, it'll help me sort out any issues for everyone else as well.

You can ping me on Discord as well if you want to go over the steps and I'll update the installation steps if needed.

**Comment by MoreColors123** [comment]
Yeah I'm still stuck and I'm on Windows 11. How can i contact you on Discord? I'm not used to it.

**Comment by ramyma** [comment]
The Discord link is https://discord.gg/RzdGa839MK

This is the running on Docker section https://github.com/ramyma/a8r8?tab=readme-ov-file#docker-1

The wsl command is when using the WSL installation method, i can now see how it might look confusing coming at the beginning of the running section. 

The read me lists all installation methods and then all running methods. Perhaps I can organize the sections by method for install / running / updating
